<?php

use Jet\Form_Field_Select;
use Jet\MVC;
use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use Jet\UI;
use Jet\Locale;
use JetApplication\Category;

/**
 * @var MVC_View $this
 * @var Form $form
 * @var Category $category
 */

$form = $this->getRaw( 'form' );
$category = $this->getRaw('category');


$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 2,
	Form_Renderer::LJ_SIZE_LARGE => 2
] );

$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 10,
	Form_Renderer::LJ_SIZE_LARGE => 8
] );

/**
 * @var Form_Field_Select $parent
 */
$parent = $form->field('parent_id');

foreach( $parent->getSelectOptions() as $option ) {
	/**
	 * @var \Jet\Data_Tree_Node $option
	 */
	
	$option->setSelectOptionCssClass( 'level-'.$option->getDepth() );
}

?>


<?= $form->start(); ?>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?= UI::button_goBack()->setUrl( MVC::getPage()->getURLPath() ) ?>
		<?php if( !$form->getIsReadonly() ): ?>
			<?= UI::button_save() ?>
		<?php endif; ?>
	</div>
</div>

<div class="row">
	<div class="col-md-2">
		<?php require 'tree.phtml'; ?>
	</div>
	<div class="col-md-10" id="main-col">

		<?= $form->field( 'parent_id' ) ?>
		<?= $form->field( 'internal_name' ) ?>
		<?= $form->field( 'internal_notes' ) ?>
		
		
		<?php foreach( $form->getSubFormPrefixes('/localized') as $locale => $prefix ):
			$locale = new Locale( $locale );
			$URL = $category->getLocalized( $locale )->getURL();
			?>
			<legend><?= UI::flag( $locale ) ?>&nbsp;<?= $locale->getName() ?></legend>
			
			<a href="<?=$URL?>" target="_blank"><?=$URL?></a>
		
			<?= $form->field( $prefix.'is_active' ) ?>
			<?= $form->field( $prefix.'title' ) ?>
			<?= $form->field( $prefix.'description' ) ?>
		<?php endforeach; ?>
	</div>
</div>
<?= $form->end(); ?>
