<?php

use Jet\MVC_Layout;
use Jet\MVC;
use Jet\Tr;

/**
 * @var MVC_Layout $this
 */

require 'parts/init_libs.php';
?>
<!DOCTYPE html>
<html lang="<?= MVC::getLocale()->getLanguage() ?>">
<head>
	<?php require 'parts/head.phtml'; ?>
</head>
<body>
<div class="container-fluid">
	<div class="page-header card text-white bg-dark">
		<div class="card-body">
			<h1><?= Tr::_( 'E-Shop' ) ?></h1>
		</div>
	</div>

	<jet_module module="UI.Web" action="breadcrumbNavigation" view="default" is_cacheable="true"/>

	<div class="row">
		<div class="col-md-1">
		</div>
		<div class="col-md-9" style="padding-top: 10px;padding-bottom: 20px;">
			<jet_layout_main_position/>
		</div>
		<div class="col-md-2">
			<div class="well well-small">
				<jet_module module="Order.Form" action="status" is_cacheable="false"/>
			</div>
			<jet_layout_position name="right"/>
		</div>
	</div>
</div>
</body>
</html>