<?php
namespace JetApplicationModule\Catalog\Browser;

use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Category;
use JetApplication\Category_Localized;
use JetApplication\Category_MenuItem;
use JetApplication\Currency;
use JetApplication\Product;

/**
 * @var MVC_View   $this
 * @var Category_Localized $category
 */

$category = $this->getRaw('category');

$subcategories = Category::getMenuTree()->getNode( $category->getCategoryId() )->getChildren();

$products = Product::getActiveByCategory( $category->getCategoryId() );
?>
<h1><?=$category->getTitle()?></h1>

<p>
	<?=$category->getDescription()?>
</p>

<?php if($subcategories): ?>
<hr>
	<?php foreach($subcategories as $subcategory):
		/**
		 * @var Category_MenuItem $subcategory
		 */
		?>
		<a href="<?=$subcategory->getURL()?>"><?=$subcategory->getLabel()?></a>
	<?php endforeach; ?>
<hr>
<?php endif; ?>

<?php if($products): ?>
	<div>
		<?php foreach($products as $product):
			$product_localized = $product->getLocalized();
			
			$main_img = $product->getImageMainThb( 200, 200 );
			?>
		<div class="card" style="width: 30%">
			<div class="card-body">
				<a href="<?=$product_localized->getURL()?>?c=<?=$category->getCategoryId()?>"><?=$product_localized->getName()?></a>
				<br>
				<img src="<?=$main_img?>" alt="<?=$product_localized->getName()?>">
				<br>
				<p>
					<?=Tr::_('Konečná cena: %price%', [
						'price' => Currency::format( $product_localized->getPrice() )
					])?>
				</p>
				
			</div>
		</div>
		<?php endforeach; ?>
	</div>
<?php endif; ?>
