<?php
namespace JetApplicationModule\ShoppingCart;

use Jet\MVC;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Application_Shop;
use JetApplication\Currency;
use JetApplication\ShoppingCart;

/**
 * @var MVC_View   $this
 */

$cart = ShoppingCart::get();
?>

<?=UI::icon('cart-shopping')?> (<?=$cart->getQty()?>)
<br>
<?=Currency::format( $cart->getValue() ) ?>

<?php if(
	$cart->getQty() &&
	MVC::getPage()->getId()!=Application_Shop::getCartPage()->getId()
):?>
	<br>
	<?=UI::button(Tr::_('Objednat'))->setUrl( Application_Shop::getCartPage()->getURL() )->setClass('success') ?>
<?php endif; ?>
