<?php
namespace JetApplicationModule\ShoppingCart;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\ShoppingCart;

/**
 * @var MVC_View   $this
 */

$cart = ShoppingCart::get();

$popup = UI::dialog('cart-popup', Tr::_('Položka přidána'));
?>
<div id="cart-icon">
	<?php require 'cart-icon.phtml'; ?>
</div>

<?=$popup->start()?>
<div id="cart-new-item">
</div>
<?=$popup->end()?>

<script>
	const ShoppingCart = {
		request: (action, onDone) => {
			$.ajax({
				url: action,
				dataType: 'json'
			}).then(function (response) {
				for( let id in response ) {
					$('#'+id).html( response[id] )
				}

				if(onDone) {
					onDone();
				}
			});
		},
		
		add: ( product_id ) => {
			ShoppingCart.request('?cart_add='+product_id, function () {
				$('#cart-popup').modal('show');
			});
		},

		plus: ( product_id ) => {
			ShoppingCart.request('?cart_plus='+product_id);
		},

		minus: ( product_id ) => {
			ShoppingCart.request('?cart_minus='+product_id);
		},

		delete: ( product_id ) => {
			ShoppingCart.request('?cart_delete='+product_id);
		}
	};
</script>