<?php
namespace JetApplicationModule\ShoppingCart;

use Jet\Locale;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use JetApplication\Application_Shop;
use JetApplication\Currency;
use JetApplication\ShoppingCart;

/**
 * @var MVC_View   $this
 */

$cart = ShoppingCart::get();

if($cart->getQty()):
?>
<table class="table table-striped">
	<?php foreach($cart->getItems() as $item):
		$product= $item->getProduct();
		$product_localized = $product->getLocalized();
		?>
	<tr>
		<td><?=UI::button_delete(' ')->setOnClick("ShoppingCart.delete({$item->getProductId()})")?></td>
		<td><img src="<?=$product->getImageMainThb(50, 50)?>"></td>
		<td><a href="<?=$product_localized->getURL()?>"><?=$product_localized->getName()?></a></td>
		<td>
			<?=UI::button('-')->setOnClick("ShoppingCart.minus({$item->getProductId()})")?>
			<?=Locale::int( $item->getQty() )?>
			<?=UI::button('+')->setOnClick("ShoppingCart.plus({$item->getProductId()})")?>
		</td>
		<td><?=Currency::format( $product_localized->getPrice()*$item->getQty() )?></td>
	</tr>
	<?php endforeach; ?>
</table>
<div class="text-right">
	<?=UI::button( Tr::_('Pokračovat v objednávce') )->setUrl( Application_Shop::getOrderPage()->getURL() )->setClass('primary')?>
</div>

<?php else: ?>
<h3><?=Tr::_('Váš košík je prázdný')?></h3>
<?php endif; ?>
