<?php

use Jet\Form_Field_Select;
use Jet\MVC;
use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;
use Jet\UI;
use Jet\Locale;
use JetApplication\Product;

/**
* @var MVC_View $this
* @var Form $form
 * @var Product $product
*/

$form = $this->getRaw( 'form' );
$product=  $this->getRaw('product');

$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 2,
	Form_Renderer::LJ_SIZE_LARGE => 2
] );

$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_EXTRA_SMALL => 12,
	Form_Renderer::LJ_SIZE_SMALL => 12,
	Form_Renderer::LJ_SIZE_MEDIUM => 10,
	Form_Renderer::LJ_SIZE_LARGE => 8
] );

/**
 * @var Form_Field_Select $category_field
 */
$category_field = $form->field( 'categories' );

foreach($category_field->getSelectOptions() as $option) {
	$option->setSelectOptionCssStyle('padding-left: '.($option->getDepth()*20).'px');
}

$category_field->input()->addCustomCssStyle('height: 400px');


?>


<?= $form->start(); ?>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?= UI::button_goBack()->setUrl( MVC::getPage()->getURLPath() ) ?>
		<?php if( !$form->getIsReadonly() ): ?>
			<?= UI::button_save() ?>
		<?php endif; ?>
	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?= $form->field( 'internal_name' ) ?>
		<?= $form->field( 'internal_notes' ) ?>
		<?= $form->field( 'internal_code' ) ?>
		<?= $form->field( 'EAN' ) ?>
		<?= $form->field( 'supplier_code' ) ?>
		
		<?php if(($img=$product->getImageMain())):?>
		<div class="row">
			<div class="col-2"></div>
			<div class="col-10">
				<a href="<?=$img?>" target="_blank"><img src="<?=$img?>" style="max-width: 300px;height: auto;"></a>
			</div>
		</div>
		<?php endif; ?>
		
		<?= $form->field( 'image_main' ) ?>
		<?= $form->field( 'categories' ) ?>
		
		<?php foreach( $form->getSubFormPrefixes('/localized') as $locale => $prefix ):
			$locale = new Locale( $locale );
			$URL = $product?->getLocalized( $locale )->getURL();
			?>
			<legend><?= UI::flag( $locale ) ?>&nbsp;<?= $locale->getName() ?></legend>

			<a href="<?=$URL?>" target="_blank"><?=$URL?></a>
		
			<?= $form->field( $prefix.'is_active' ) ?>
			<?= $form->field( $prefix.'name' ) ?>
			<?= $form->field( $prefix.'description' ) ?>
			<?= $form->field( $prefix.'price' ) ?>
			<?= $form->field( $prefix.'vat_rate' ) ?>
		<?php endforeach; ?>
	</div>
</div>
<?= $form->end(); ?>
