<?php
namespace JetApplicationModule\Catalog\Browser;

use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Currency;
use JetApplication\Product;

/**
 * @var MVC_View   $this
 * @var Product $product
 */

$product = $this->getRaw('product');
$product_localized = $product->getLocalized();

$main_img = $product->getImageMainThb( 300, 300 );
?>
<h1><?=$product_localized->getName()?></h1>

<img src="<?=$main_img?>" alt="<?=$product_localized->getName()?>">

<p>
	<?=$product_localized->getDescription()?>
</p>

<p>
	<?=Tr::_('Konečná cena: %price%', [
			'price' => Currency::format( $product_localized->getPrice() )
	])?>
</p>